### ISSUE TITLE
Failed to activate the de-workbench package

### ISSUE THREAD

**Issue by inceptusp** [github-vipera/de-workbench#2]
[Enter steps to reproduce:]

1. When installing the package

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: elementary OS
**Thrown From**: [de-workbench](https://github.com/github-vipera/de-workbench) package 0.1.13

### Stack Trace

Failed to activate the de-workbench package

```
At Cannot find module '../DEWorkbench/DEWBResourceManager'

Error: Cannot find module '../DEWorkbench/DEWBResourceManager'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/usr/share/atom/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/de-workbench/lib/cordova/CordovaExecutor.js:10:46)
    at /packages/de-workbench/lib/cordova/CordovaExecutor.js:13:29)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/de-workbench/lib/cordova/Cordova.js:18:42)
    at /packages/de-workbench/lib/cordova/Cordova.js:38:21)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/de-workbench/lib/DEWorkbench/ProjectManager.js:2:38)
    at /packages/de-workbench/lib/DEWorkbench/ProjectManager.js:7:28)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

### Commands

```
     -1:56.5.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
de-workbench 0.1.13 
```

**Comment by github-vipera** [comment]
Hi Pedro
all this is very strange and I would like to understand if you are installing the package from ATOM or from the Git repository.
I see you're using elementary OS, unfortunately I do not have the possibility to do tests on this platform, and then i ask you to try this if you can and send me the error you get:

1 - clone this repository
2 - run a "npm install"
3 - run a "npm run compile"
4 - run an "apm install"
5 - execute an "apm link"
 
thank you

regards 
Marco

**Comment by marcobonati** [comment]
Hi Pedro
all this is very strange and I would like to understand if you are installing the package from ATOM or from the Git repository.
I see you're using elementary OS, unfortunately I do not have the possibility to do tests on this platform, and then i ask you to try this if you can and send me the error you get:

1 - clone this repository
2 - run a "npm install"
3 - run a "npm run compile"
4 - run an "apm install"
5 - execute an "apm link"
 
thank you

regards
Marco

**Comment by alecaroz7** [comment]
Hi @marcobonati ,  This is the output,

**Package Atom:**

`user@ debian:de-workbench $ npm run compile

> de-workbench@0.1.13 compile /home/user/Development/cordoba/de-workbench
> tsc

src/element/input.ts(11,17): error TS4058: Return type of exported function has or is using name 'TextEditorElement' from external module "/home/user/Development/cordoba/de-workbench/node_modules/@types/atom/index" but cannot be named.
src/ui-components/UIModalView.ts(26,20): error TS2503: Cannot find namespace 'AtomCore'.
src/ui-components/UIModalView.ts(26,20): error TS4031: Public property 'panel' of exported class has or is using private name 'AtomCore'.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! de-workbench@0.1.13 compile: `tsc`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the de-workbench@0.1.13 compile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2018-01-18T00_58_49_353Z-debug.log
user@ debian:de-workbench $ 
user@ debian:de-workbench $ 
user@ debian:de-workbench $ apm install
Installing modules ✓
user@ debian:de-workbench $ apm link
/home/user/.atom/packages/de-workbench -> /home/user/Development/cordoba/de-workbench`



**SO:**
`# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.0 (stretch)
Release:        9.0
Codename:       stretch
`
`# uname -a
Linux debian 4.9.0-1-amd64 #1 SMP Debian 4.9.6-3 (2017-01-28) x86_64 GNU/Linux
`

**Comment by marcobonati** [comment]
Hi @alecaroz7 
i opened the 0.1.14 branch with a fix.
Can you tell me if it solves your compilation problem?

regards

**Comment by huseyinkozan** [comment]
Same at Ubuntu 16.04. 
Compiles and installs as you described, but nothing works.
